// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ParameterSetUpdateMessage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace MarketDataDistributionService.Messages {

  /// <summary>Holder for reflection information generated from ParameterSetUpdateMessage.proto</summary>
  public static partial class ParameterSetUpdateMessageReflection {

    #region Descriptor
    /// <summary>File descriptor for ParameterSetUpdateMessage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ParameterSetUpdateMessageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9QYXJhbWV0ZXJTZXRVcGRhdGVNZXNzYWdlLnByb3RvGh9nb29nbGUvcHJv",
            "dG9idWYvdGltZXN0YW1wLnByb3RvIoUCChlQYXJhbWV0ZXJTZXRVcGRhdGVN",
            "ZXNzYWdlEhEKCXVuZGVybGllchgBIAEoCRIPCgdzcG90X3B4GAIgASgBEhYK",
            "DnZvbGF0aWxpdHlfcGN0GAMgASgBEhoKEnJpc2tfZnJlZV9yYXRlX3BjdBgE",
            "IAEoARIaChJkaXZpZGVuZF95aWVsZF9wY3QYBSABKAESLwoLZXhwaXJ5X2Rh",
            "dGUYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhQKDHN0cmlr",
            "ZV9wcmljZRgHIAEoARItCglwcmljZVRpbWUYCCABKAsyGi5nb29nbGUucHJv",
            "dG9idWYuVGltZXN0YW1wQimqAiZNYXJrZXREYXRhRGlzdHJpYnV0aW9uU2Vy",
            "dmljZS5NZXNzYWdlc2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::MarketDataDistributionService.Messages.ParameterSetUpdateMessage), global::MarketDataDistributionService.Messages.ParameterSetUpdateMessage.Parser, new[]{ "Underlier", "SpotPx", "VolatilityPct", "RiskFreeRatePct", "DividendYieldPct", "ExpiryDate", "StrikePrice", "PriceTime" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ParameterSetUpdateMessage : pb::IMessage<ParameterSetUpdateMessage>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParameterSetUpdateMessage> _parser = new pb::MessageParser<ParameterSetUpdateMessage>(() => new ParameterSetUpdateMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParameterSetUpdateMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::MarketDataDistributionService.Messages.ParameterSetUpdateMessageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParameterSetUpdateMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParameterSetUpdateMessage(ParameterSetUpdateMessage other) : this() {
      underlier_ = other.underlier_;
      spotPx_ = other.spotPx_;
      volatilityPct_ = other.volatilityPct_;
      riskFreeRatePct_ = other.riskFreeRatePct_;
      dividendYieldPct_ = other.dividendYieldPct_;
      expiryDate_ = other.expiryDate_ != null ? other.expiryDate_.Clone() : null;
      strikePrice_ = other.strikePrice_;
      priceTime_ = other.priceTime_ != null ? other.priceTime_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParameterSetUpdateMessage Clone() {
      return new ParameterSetUpdateMessage(this);
    }

    /// <summary>Field number for the "underlier" field.</summary>
    public const int UnderlierFieldNumber = 1;
    private string underlier_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Underlier {
      get { return underlier_; }
      set {
        underlier_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "spot_px" field.</summary>
    public const int SpotPxFieldNumber = 2;
    private double spotPx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SpotPx {
      get { return spotPx_; }
      set {
        spotPx_ = value;
      }
    }

    /// <summary>Field number for the "volatility_pct" field.</summary>
    public const int VolatilityPctFieldNumber = 3;
    private double volatilityPct_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double VolatilityPct {
      get { return volatilityPct_; }
      set {
        volatilityPct_ = value;
      }
    }

    /// <summary>Field number for the "risk_free_rate_pct" field.</summary>
    public const int RiskFreeRatePctFieldNumber = 4;
    private double riskFreeRatePct_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double RiskFreeRatePct {
      get { return riskFreeRatePct_; }
      set {
        riskFreeRatePct_ = value;
      }
    }

    /// <summary>Field number for the "dividend_yield_pct" field.</summary>
    public const int DividendYieldPctFieldNumber = 5;
    private double dividendYieldPct_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double DividendYieldPct {
      get { return dividendYieldPct_; }
      set {
        dividendYieldPct_ = value;
      }
    }

    /// <summary>Field number for the "expiry_date" field.</summary>
    public const int ExpiryDateFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp expiryDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ExpiryDate {
      get { return expiryDate_; }
      set {
        expiryDate_ = value;
      }
    }

    /// <summary>Field number for the "strike_price" field.</summary>
    public const int StrikePriceFieldNumber = 7;
    private double strikePrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StrikePrice {
      get { return strikePrice_; }
      set {
        strikePrice_ = value;
      }
    }

    /// <summary>Field number for the "priceTime" field.</summary>
    public const int PriceTimeFieldNumber = 8;
    private global::Google.Protobuf.WellKnownTypes.Timestamp priceTime_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp PriceTime {
      get { return priceTime_; }
      set {
        priceTime_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParameterSetUpdateMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParameterSetUpdateMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Underlier != other.Underlier) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SpotPx, other.SpotPx)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(VolatilityPct, other.VolatilityPct)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(RiskFreeRatePct, other.RiskFreeRatePct)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(DividendYieldPct, other.DividendYieldPct)) return false;
      if (!object.Equals(ExpiryDate, other.ExpiryDate)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StrikePrice, other.StrikePrice)) return false;
      if (!object.Equals(PriceTime, other.PriceTime)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Underlier.Length != 0) hash ^= Underlier.GetHashCode();
      if (SpotPx != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SpotPx);
      if (VolatilityPct != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(VolatilityPct);
      if (RiskFreeRatePct != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(RiskFreeRatePct);
      if (DividendYieldPct != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(DividendYieldPct);
      if (expiryDate_ != null) hash ^= ExpiryDate.GetHashCode();
      if (StrikePrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StrikePrice);
      if (priceTime_ != null) hash ^= PriceTime.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Underlier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Underlier);
      }
      if (SpotPx != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(SpotPx);
      }
      if (VolatilityPct != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(VolatilityPct);
      }
      if (RiskFreeRatePct != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RiskFreeRatePct);
      }
      if (DividendYieldPct != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(DividendYieldPct);
      }
      if (expiryDate_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ExpiryDate);
      }
      if (StrikePrice != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(StrikePrice);
      }
      if (priceTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(PriceTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Underlier.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Underlier);
      }
      if (SpotPx != 0D) {
        output.WriteRawTag(17);
        output.WriteDouble(SpotPx);
      }
      if (VolatilityPct != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(VolatilityPct);
      }
      if (RiskFreeRatePct != 0D) {
        output.WriteRawTag(33);
        output.WriteDouble(RiskFreeRatePct);
      }
      if (DividendYieldPct != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(DividendYieldPct);
      }
      if (expiryDate_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ExpiryDate);
      }
      if (StrikePrice != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(StrikePrice);
      }
      if (priceTime_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(PriceTime);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Underlier.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlier);
      }
      if (SpotPx != 0D) {
        size += 1 + 8;
      }
      if (VolatilityPct != 0D) {
        size += 1 + 8;
      }
      if (RiskFreeRatePct != 0D) {
        size += 1 + 8;
      }
      if (DividendYieldPct != 0D) {
        size += 1 + 8;
      }
      if (expiryDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ExpiryDate);
      }
      if (StrikePrice != 0D) {
        size += 1 + 8;
      }
      if (priceTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PriceTime);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParameterSetUpdateMessage other) {
      if (other == null) {
        return;
      }
      if (other.Underlier.Length != 0) {
        Underlier = other.Underlier;
      }
      if (other.SpotPx != 0D) {
        SpotPx = other.SpotPx;
      }
      if (other.VolatilityPct != 0D) {
        VolatilityPct = other.VolatilityPct;
      }
      if (other.RiskFreeRatePct != 0D) {
        RiskFreeRatePct = other.RiskFreeRatePct;
      }
      if (other.DividendYieldPct != 0D) {
        DividendYieldPct = other.DividendYieldPct;
      }
      if (other.expiryDate_ != null) {
        if (expiryDate_ == null) {
          ExpiryDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ExpiryDate.MergeFrom(other.ExpiryDate);
      }
      if (other.StrikePrice != 0D) {
        StrikePrice = other.StrikePrice;
      }
      if (other.priceTime_ != null) {
        if (priceTime_ == null) {
          PriceTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        PriceTime.MergeFrom(other.PriceTime);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Underlier = input.ReadString();
            break;
          }
          case 17: {
            SpotPx = input.ReadDouble();
            break;
          }
          case 25: {
            VolatilityPct = input.ReadDouble();
            break;
          }
          case 33: {
            RiskFreeRatePct = input.ReadDouble();
            break;
          }
          case 41: {
            DividendYieldPct = input.ReadDouble();
            break;
          }
          case 50: {
            if (expiryDate_ == null) {
              ExpiryDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpiryDate);
            break;
          }
          case 57: {
            StrikePrice = input.ReadDouble();
            break;
          }
          case 66: {
            if (priceTime_ == null) {
              PriceTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PriceTime);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Underlier = input.ReadString();
            break;
          }
          case 17: {
            SpotPx = input.ReadDouble();
            break;
          }
          case 25: {
            VolatilityPct = input.ReadDouble();
            break;
          }
          case 33: {
            RiskFreeRatePct = input.ReadDouble();
            break;
          }
          case 41: {
            DividendYieldPct = input.ReadDouble();
            break;
          }
          case 50: {
            if (expiryDate_ == null) {
              ExpiryDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ExpiryDate);
            break;
          }
          case 57: {
            StrikePrice = input.ReadDouble();
            break;
          }
          case 66: {
            if (priceTime_ == null) {
              PriceTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(PriceTime);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
